services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile.${STAGE:-development}
    container_name: node
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${STAGE}
 
