version: "3.9"
services:
  dev:
    build:
      context: .
      target: development
    ports:
      - "8090:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped

  prod:
    build:
      context: .
      target: production
    ports:
      - "8090:3000"
    environment:
      - NODE_ENV=production
    command: npm run start
    restart: unless-stopped
