services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST=al-nourgroup.com,www.al-nourgroup.com
      - LETSENCRYPT_HOST=al-nourgroup.com,www.al-nourgroup.com
      - LETSENCRYPT_EMAIL=you@example.com

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=you@example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - acme:/etc/acme.sh

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  acme:
