FROM node:lts-alpine3.22

RUN apk add --no-cache libc6-compat
RUN npm i -g npm

EXPOSE 3000

ENV PORT 3000
ENV NODE_ENV development

WORKDIR /app

COPY package.json .
COPY package-lock.json .

COPY . .


CMD [ "npm", "run","dev" ]
# CMD [ "serve", "out", "-l", "3000" ]